version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - uid=1000
        - user=dev
    container_name: isabelle_app
    restart: always
    # O fuso horário agora é herdado do Dockerfile, mas manter aqui reforça a config
    environment:
      - TZ=America/Araguaina
    volumes:
      - ./:/var/www
    ports:
      - "9003:9000"
      - "5173:5173" # <--- PORTA DO VITE ADICIONADA AQUI
    working_dir: /var/www
    networks:
      - network_isabelle

    healthcheck:
      test: ["CMD", "php", "artisan", "doctor"]
      interval: 30s
      timeout: 10s
      retries: 3

  webserver:
    image: nginx:alpine
    container_name: nginx_isabelle
    restart: always
    ports:
      - "8005:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - network_isabelle

  db:
    image: mysql:8.0
    container_name: db_isabelle
    restart: always
    environment:
      # Fuso horário
      TZ: America/Araguaina
      # O Docker vai ler os valores abaixo diretamente do arquivo .env
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3309:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - network_isabelle

networks:
  network_isabelle:
    driver: bridge

volumes:
  dbdata:
